### ISSUE TITLE
A question regarding Uyghur IPA

### ISSUE THREAD

**Issue by neouyghur** [IS2AI/TurkicTTS#1]
Salam, Great work and thanks for adding Uyghur. I have a simple question. I found that your IPA mapping table is slightly different from what I saw from WIKI.  Is it because you are avoiding two-letter IPA?

**Comment by yeshpanovrustem** [comment]
Salem!

Thank you for your kind words. We appreciate your interest in our project. Regarding the IPA mapping table, you are correct that there might be slight differences compared to what you found on WIKI or other sources.

The reason behind these differences is not to avoid two-letter IPA representations intentionally. Instead, the IPA mapping in our project is based on various linguistic sources and our expertise to ensure accuracy and consistency with the specific requirements of our project. While we strive to provide a comprehensive and accurate representation, slight variations might occur due to the availability of different sources and considerations specific to the scope of our project.

If you have any specific observations or suggestions regarding the IPA mapping, we would be more than happy to hear them. Our goal is to continually improve and refine our language support, and community feedback plays a crucial role in achieving that.

Once again, we are grateful for your interest and support. If you have any further questions or comments, feel free to share them.

**Comment by neouyghur** [comment]
Thanks for your reply. It clarifies my question. I am trying to implement the same Uyghur API converter and it to the [Uyghur Script Converter](https://github.com/neouyghur/ScriptConverter4Uyghur).

**Comment by yeshpanovrustem** [comment]
You are welcome! That sounds like a great initiative. Best of luck with your implementation of the Uyghur API converter and its integration into the Uyghur Script Converter. Happy coding!
